version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        dependency-type: 'production'
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase-if-necessary
    groups:
      safe-dependencies:
        update-types: ['minor', 'patch']
      major-dependencies:
        update-types: ['major']
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
